name: Test linux job
on:
  push

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script file
        run: |
           chmod +x ./public/scripts/test.sh
           ./public/scripts/test.sh
        shell: bash

      - name: Run Bash script
        run: bash bash.sh

      - name: Ready Json
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Write Json
        run: |
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'

      - name: Write Json Second
        run: |
          echo '${{ fromJson(env.PACKAGE_JSON).scripts.start }}'
